### PR TITLE
Profile

### PR DESCRIPTION
**Pull request by widespaceDLS**
Looks good, ready to merge following this commit of Jan 8, if you don't see any issues Misha

---

needing to prohibit editing of 'member_id'  ****************\*  Without eliminating it from schema

### CODE REVIEW

**Comment by mishavee** [comment]
Hi Tom, a consequence of removing member_key from the schema, is: admin user is created without a member_key, and a new user fails to create an entry in "people", with the following error:
insert failed: MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.People.$c2_member_key  dup key: { : null }

**Comment by mishavee** [comment]
I didn't test with a clean database, let me know if that is required.

**Comment by widespaceDLS** [comment]
yes, that may be a problem! I'll check it outt.

```
  From: Misha Verplak <notifications@github.com>
```

 To: GrowSocial/pilot pilot@noreply.github.com 
Cc: thomas carroll dawnlightsmile@yahoo.com
 Sent: Thursday, January 7, 2016 8:35 PM
 Subject: Re: [pilot] Profile (#79)

Hi Tom, a consequence of removing member_key from the schema, is: admin user is created without a member_key, and a new user fails to create an entry in "people", with the following error:
insert failed: MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.People.$c2_member_key dup key: { : null }—

**Comment by widespaceDLS** [comment]
no. that isn't it.    That field has to be in the schema apparently. The new People records are not being created with a member_key.
The complication is that when fields are specified for display, the autoform object is not being generated. Another idea could be to use a secondary schema, but it is being ignored. The first schema attached to the People collection is used by quickForm apparently, without an option.

I'll need to test more. Maybe go out to Stackoverflow and ask around.   I'm pretty stumped on this, it's been a week now not able to do more than use the simple version 'quickForm'Unless we know a way to write that record create with another method. There ought to be a way to do that. Or, drop a schema and attach a new one when needed 

I'm at end of day here now, I'll be back on it tomorrow
T.

```
  From: Misha Verplak <notifications@github.com>
```

 To: GrowSocial/pilot pilot@noreply.github.com 
Cc: thomas carroll dawnlightsmile@yahoo.com
 Sent: Thursday, January 7, 2016 8:39 PM
 Subject: Re: [pilot] Profile (#79)

I didn't test with a clean database, let me know if that is required.—

**Comment by mishavee** [comment]
According to quickform doc, in the attributes you can specify "fields" to include, or specify "omitFields" to exclude:
https://github.com/aldeed/meteor-autoform#quickform
It points to example: http://autoform.meteor.com/qfdetails
Look at second example under section "Choosing Fields":
inclusive fields: {{> quickForm id="fields2" schema=Schemas.FieldsExamples fields="name,contacts"}}
I'd go for this approach, listing specific fields to edit, otherwise you'd need to know every field not relevant to the edit from that page.

**Comment by widespaceDLS** [comment]
good catch.in my hurry, I never scrolled down to further examples .. frustrated with the first few approaches and keen to pry them open
even still, only a modified approach is working. I am not able to reproduce certain aspects.  But we have a solution now - I'm uploading today.

I haven't been able to use the schema parameter. My next stop would be Stackoverflow community 
-- and leaving the tests and other examples there in code as comments-- As well as mentioning the problems / mysteries attempting #autoform and afQuickFields.  
Limited to quickForm we can't specialize the form, formatting, making pretty. There are many validation features in Autoform that will ultimately be useful

Also leaving some other extended documentation and commentary regarding the load of profile template, regarding testing for admin user, 'psuedo_0'

```
  From: Misha Verplak <notifications@github.com>
```

 To: GrowSocial/pilot pilot@noreply.github.com 
Cc: thomas carroll dawnlightsmile@yahoo.com
 Sent: Friday, January 8, 2016 12:20 AM
 Subject: Re: [pilot] Profile (#79)

According to quickform doc, in the attributes you can specify "fields" to include, or specify "omitFields" to exclude:
https://github.com/aldeed/meteor-autoform#quickform
It points to example: http://autoform.meteor.com/qfdetails
Look at second example under section "Choosing Fields":
inclusive fields: {{> quickForm id="fields2" schema=Schemas.FieldsExamples fields="name,contacts"}}
I'd go for this approach, listing specific fields to edit, otherwise you'd need to know every field not relevant to the edit from that page.—

**Comment by mishavee** [comment]
FYI bootstrap and jquery are already included in the packages ;)

**Comment by widespaceDLS** [comment]
did I leave a reference to them somewhere? Let me know where that code is, so I understand this better. The popup feature in profile now came through non-meteor tutorials, I experimented a bit to be sure to translate appropriately, and not be redundant.

**Comment by mishavee** [comment]
Apologies, I saw them on an intermediate commit, you've already tidied them away.
The popups look really good!
FYI I've updated Filiz's code into master, she's used the homepage as a base for the help page, and applied bootstrap to make it mobile friendlier.

**Pull request merged**
